In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.options.display.max_rows = 200
pd.options.display.max_columns = 200

**读取数据**

In [2]:
#读取数据
df = pd.read_csv('../data/LoanStats_2018Q1.csv', header = 1, low_memory=False)
df1 = pd.read_csv('../data/LoanStats_2018Q2.csv', header = 1, low_memory=False)

In [3]:
df = pd.concat([df,df1],ignore_index = True)
df.info(max_cols = 150)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238640 entries, 0 to 238639
Data columns (total 145 columns):
id                                            4 non-null object
member_id                                     0 non-null float64
loan_amnt                                     238636 non-null float64
funded_amnt                                   238636 non-null float64
funded_amnt_inv                               238636 non-null float64
term                                          238636 non-null object
int_rate                                      238636 non-null object
installment                                   238636 non-null float64
grade                                         238636 non-null object
sub_grade                                     238636 non-null object
emp_title                                     218361 non-null object
emp_length                                    218740 non-null object
home_ownership                                238636 non-null object
annual_inc                                    238636 non-null float64
verification_status                           238636 non-null object
issue_d                                       238636 non-null object
loan_status                                   238636 non-null object
pymnt_plan                                    238636 non-null object
url                                           0 non-null float64
desc                                          0 non-null float64
purpose                                       238636 non-null object
title                                         238636 non-null object
zip_code                                      238636 non-null object
addr_state                                    238636 non-null object
dti                                           238048 non-null float64
delinq_2yrs                                   238636 non-null float64
earliest_cr_line                              238636 non-null object
inq_last_6mths                                238636 non-null float64
mths_since_last_delinq                        105569 non-null float64
mths_since_last_record                        31827 non-null float64
open_acc                                      238636 non-null float64
pub_rec                                       238636 non-null float64
revol_bal                                     238636 non-null float64
revol_util                                    238329 non-null object
total_acc                                     238636 non-null float64
initial_list_status                           238636 non-null object
out_prncp                                     238636 non-null float64
out_prncp_inv                                 238636 non-null float64
total_pymnt                                   238636 non-null float64
total_pymnt_inv                               238636 non-null float64
total_rec_prncp                               238636 non-null float64
total_rec_int                                 238636 non-null float64
total_rec_late_fee                            238636 non-null float64
recoveries                                    238636 non-null float64
collection_recovery_fee                       238636 non-null float64
last_pymnt_d                                  238300 non-null object
last_pymnt_amnt                               238636 non-null float64
next_pymnt_d                                  215724 non-null object
last_credit_pull_d                            238635 non-null object
collections_12_mths_ex_med                    238636 non-null float64
mths_since_last_major_derog                   55823 non-null float64
policy_code                                   238636 non-null float64
application_type                              238636 non-null object
annual_inc_joint                              34418 non-null float64
dti_joint                                     34418 non-null float64
verification_status_joint                     33434 non-null object
acc_now_delinq                                238636 non-null float64
tot_coll_amt                                  238636 non-null float64
tot_cur_bal                                   238636 non-null float64
open_acc_6m                                   238636 non-null float64
open_act_il                                   238636 non-null float64
open_il_12m                                   238636 non-null float64
open_il_24m                                   238636 non-null float64
mths_since_rcnt_il                            229315 non-null float64
total_bal_il                                  238636 non-null float64
il_util                                       198600 non-null float64
open_rv_12m                                   238636 non-null float64
open_rv_24m                                   238636 non-null float64
max_bal_bc                                    238636 non-null float64
all_util                                      238573 non-null float64
total_rev_hi_lim                              238636 non-null float64
inq_fi                                        238636 non-null float64
total_cu_tl                                   238636 non-null float64
inq_last_12m                                  238636 non-null float64
acc_open_past_24mths                          238636 non-null float64
avg_cur_bal                                   238621 non-null float64
bc_open_to_buy                                235386 non-null float64
bc_util                                       235283 non-null float64
chargeoff_within_12_mths                      238636 non-null float64
delinq_amnt                                   238636 non-null float64
mo_sin_old_il_acct                            229315 non-null float64
mo_sin_old_rev_tl_op                          238636 non-null float64
mo_sin_rcnt_rev_tl_op                         238636 non-null float64
mo_sin_rcnt_tl                                238636 non-null float64
mort_acc                                      238636 non-null float64
mths_since_recent_bc                          235579 non-null float64
mths_since_recent_bc_dlq                      47516 non-null float64
mths_since_recent_inq                         209394 non-null float64
mths_since_recent_revol_delinq                68827 non-null float64
num_accts_ever_120_pd                         238636 non-null float64
num_actv_bc_tl                                238636 non-null float64
num_actv_rev_tl                               238636 non-null float64
num_bc_sats                                   238636 non-null float64
num_bc_tl                                     238636 non-null float64
num_il_tl                                     238636 non-null float64
num_op_rev_tl                                 238636 non-null float64
num_rev_accts                                 238636 non-null float64
num_rev_tl_bal_gt_0                           238636 non-null float64
num_sats                                      238636 non-null float64
num_tl_120dpd_2m                              232345 non-null float64
num_tl_30dpd                                  238636 non-null float64
num_tl_90g_dpd_24m                            238636 non-null float64
num_tl_op_past_12m                            238636 non-null float64
pct_tl_nvr_dlq                                238635 non-null float64
percent_bc_gt_75                              235381 non-null float64
pub_rec_bankruptcies                          238636 non-null float64
tax_liens                                     238636 non-null float64
tot_hi_cred_lim                               238636 non-null float64
total_bal_ex_mort                             238636 non-null float64
total_bc_limit                                238636 non-null float64
total_il_high_credit_limit                    238636 non-null float64
revol_bal_joint                               34418 non-null float64
sec_app_earliest_cr_line                      34418 non-null object
sec_app_inq_last_6mths                        34418 non-null float64
sec_app_mort_acc                              34418 non-null float64
sec_app_open_acc                              34418 non-null float64
sec_app_revol_util                            33789 non-null float64
sec_app_open_act_il                           34418 non-null float64
sec_app_num_rev_accts                         34418 non-null float64
sec_app_chargeoff_within_12_mths              34418 non-null float64
sec_app_collections_12_mths_ex_med            34418 non-null float64
sec_app_mths_since_last_major_derog           11611 non-null float64
hardship_flag                                 238636 non-null object
hardship_type                                 104 non-null object
hardship_reason                               104 non-null object
hardship_status                               104 non-null object
deferral_term                                 104 non-null float64
hardship_amount                               104 non-null float64
hardship_start_date                           104 non-null object
hardship_end_date                             104 non-null object
payment_plan_start_date                       104 non-null object
hardship_length                               104 non-null float64
hardship_dpd                                  104 non-null float64
hardship_loan_status                          104 non-null object
orig_projected_additional_accrued_interest    99 non-null float64
hardship_payoff_balance_amount                104 non-null float64
hardship_last_payment_amount                  104 non-null float64
disbursement_method                           238636 non-null object
debt_settlement_flag                          238636 non-null object
debt_settlement_flag_date                     110 non-null object
settlement_status                             110 non-null object
settlement_date                               110 non-null object
settlement_amount                             110 non-null float64
settlement_percentage                         110 non-null float64
settlement_term                               110 non-null float64
dtypes: float64(107), object(38)
memory usage: 264.0+ MB

In [4]:
df.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
238635,NaN,NaN,14000.0,14000.0,13975.0,36 months,16.01%,492.27,C,C5,client analyst,10+ years,MORTGAGE,52874.0,Not Verified,Apr-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,912xx,CA,22.36,0.0,Sep-1995,1.0,NaN,87.0,9.0,1.0,25426.0,85%,20.0,f,11774.07,11753.05,3433.44,3427.31,2225.93,1207.51,0.0,0.0,0.0,Nov-2018,492.27,Dec-2018,Nov-2018,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,32056.0,2.0,1.0,1.0,1.0,6.0,6630.0,88.0,1.0,2.0,8552.0,85.0,29900.0,1.0,1.0,1.0,3.0,3561.0,5520.0,91.0,0.0,0.0,6.0,270.0,4.0,4.0,0.0,15.0,NaN,6.0,NaN,0.0,5.0,8.0,10.0,10.0,1.0,8.0,19.0,7.0,9.0,NaN,0.0,0.0,2.0,100.0,80.0,1.0,0.0,37400.0,32056.0,27600.0,7500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
238636,NaN,NaN,7500.0,7500.0,7500.0,36 months,10.90%,245.19,B,B4,Residence Counselor,10+ years,RENT,126000.0,Not Verified,Apr-2018,Current,n,NaN,NaN,other,Other,125xx,NY,6.33,0.0,Dec-1986,1.0,NaN,NaN,16.0,0.0,11122.0,28.3%,31.0,f,6226.25,6226.25,1707.25,1707.25,1273.75,433.50,0.0,0.0,0.0,Nov-2018,245.19,Dec-2018,Nov-2018,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,132066.0,1.0,0.0,0.0,0.0,68.0,0.0,NaN,5.0,8.0,5564.0,28.0,39300.0,1.0,0.0,2.0,11.0,8254.0,23906.0,31.1,0.0,0.0,146.0,375.0,1.0,1.0,3.0,1.0,NaN,1.0,NaN,0.0,9.0,11.0,11.0,16.0,4.0,15.0,24.0,11.0,16.0,0.0,0.0,0.0,5.0,100.0,0.0,0.0,0.0,162600.0,11122.0,34700.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
238637,NaN,NaN,35000.0,35000.0,35000.0,36 months,6.07%,1065.88,A,A2,Founder,10+ years,RENT,110000.0,Source Verified,Apr-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,341xx,FL,9.80,0.0,Jul-1995,0.0,NaN,NaN,13.0,0.0,39634.0,35.2%,21.0,w,28682.91,28682.91,7449.36,7449.36,6317.09,1132.27,0.0,0.0,0.0,Nov-2018,1065.88,Dec-2018,Nov-2018,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,39634.0,2.0,0.0,0.0,0.0,73.0,0.0,NaN,2.0,3.0,14352.0,35.0,112500.0,0.0,0.0,0.0,3.0,3049.0,49561.0,43.3,0.0,0.0,157.0,272.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,0.0,6.0,7.0,9.0,9.0,5.0,13.0,14.0,7.0,13.0,0.0,0.0,0.0,2.0,100.0,44.4,0.0,0.0,112500.0,39634.0,87400.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
238638,Total amount funded in policy code 1: 2080429200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238639,Total amount funded in policy code 2: 737901574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

数据来自于 Lending Club  
https://www.lendingclub.com/info/download-data.action

In [5]:
#对于变量类型为obejct的数据进行察看
df.select_dtypes(include = ['O']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238640 entries, 0 to 238639
Data columns (total 38 columns):
id                           4 non-null object
term                         238636 non-null object
int_rate                     238636 non-null object
grade                        238636 non-null object
sub_grade                    238636 non-null object
emp_title                    218361 non-null object
emp_length                   218740 non-null object
home_ownership               238636 non-null object
verification_status          238636 non-null object
issue_d                      238636 non-null object
loan_status                  238636 non-null object
pymnt_plan                   238636 non-null object
purpose                      238636 non-null object
title                        238636 non-null object
zip_code                     238636 non-null object
addr_state                   238636 non-null object
earliest_cr_line             238636 non-null object
revol_util                   238329 non-null object
initial_list_status          238636 non-null object
last_pymnt_d                 238300 non-null object
next_pymnt_d                 215724 non-null object
last_credit_pull_d           238635 non-null object
application_type             238636 non-null object
verification_status_joint    33434 non-null object
sec_app_earliest_cr_line     34418 non-null object
hardship_flag                238636 non-null object
hardship_type                104 non-null object
hardship_reason              104 non-null object
hardship_status              104 non-null object
hardship_start_date          104 non-null object
hardship_end_date            104 non-null object
payment_plan_start_date      104 non-null object
hardship_loan_status         104 non-null object
disbursement_method          238636 non-null object
debt_settlement_flag         238636 non-null object
debt_settlement_flag_date    110 non-null object
settlement_status            110 non-null object
settlement_date              110 non-null object
dtypes: object(38)
memory usage: 69.2+ MB

对于评分卡建立来说，term,grade,sub_grade,issue_d,title均属于贷后数据因此决定删除。但是loan_status对于我们进行数据标记有用处，所以不删除。

In [6]:
#对于变量类型为obejct的数据进行察看
df.select_dtypes(include = ['O']).head()

,id,term,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,earliest_cr_line,revol_util,initial_list_status,last_pymnt_d,next_pymnt_d,last_credit_pull_d,application_type,verification_status_joint,sec_app_earliest_cr_line,hardship_flag,hardship_type,hardship_reason,hardship_status,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_loan_status,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date
0,NaN,60 months,16.01%,C,C5,Case Manager Associate,2 years,OWN,Not Verified,Mar-2018,Current,n,debt_consolidation,Debt consolidation,328xx,FL,Oct-1993,36.1%,w,Nov-2018,Dec-2018,Nov-2018,Individual,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN
1,NaN,60 months,14.07%,C,C3,Teacher,4 years,RENT,Source Verified,Mar-2018,Current,n,major_purchase,Major purchase,341xx,FL,Oct-2004,15.7%,w,Nov-2018,Dec-2018,Nov-2018,Individual,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN
2,NaN,36 months,10.41%,B,B3,Teacher,10+ years,MORTGAGE,Not Verified,Mar-2018,Current,n,medical,Medical expenses,786xx,TX,Sep-2000,21.1%,w,Nov-2018,Dec-2018,Nov-2018,Individual,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN
3,NaN,36 months,7.96%,A,A5,Occupational Therapist,3 years,MORTGAGE,Not Verified,Mar-2018,Current,n,other,Other,481xx,MI,Aug-2011,74.5%,w,Nov-2018,Dec-2018,Nov-2018,Individual,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN
4,NaN,36 months,6.07%,A,A2,Credit Director,10+ years,OWN,Source Verified,Mar-2018,Current,n,house,Home buying,117xx,NY,Mar-1994,11.3%,w,Nov-2018,Dec-2018,Nov-2018,Individual,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN

发现：  
1.从这里可以发现，id这一栏数据只有2个非空，而其他的数据最多的只有238636行，这两个加起来正好238640也就是总的数据条数，这就说明有可能是这4条变量本身就是空的，需要察看。  
2.hardship_flag代表着困难情况，具体里面的数据代表的含义，之后进行分析。  
3.verification_status_joint,sec_app_earliest_cr_line,等变量数量太少，不进行分析。(本次分析按照65%的阈值来进行删除)。
4.emp_title,emp_length这两个字段的缺失值较少的字段需要填充。  
5.int_rate, revol_util这两个本应该为数字的字段这里是用字符串表示的，为了之后的计算方便，需要更改类型。

In [7]:
#察看id 不为空的字段的信息
df.loc[df.id.notnull()]

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
107864,Total amount funded in policy code 1: 1741781700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107865,Total amount funded in policy code 2: 564202131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238638,Total amount funded in policy code 1: 2080429200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238639,Total amount funded in policy code 2: 737901574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

可以发现这4条数据中基本没有信息，因此决定删除。

In [8]:
#察看issue_d
df.issue_d.value_counts()

May-2018    46311
Apr-2018    42928
Jun-2018    41533
Mar-2018    38771
Jan-2018    36347
Feb-2018    32746
Name: issue_d, dtype: int64

符合本次数据集的时间区段的时间含义，借款发生的时间为1-6月，并且和为238636，说明没有缺失的放贷日期。不过放贷时间对于评分卡构建没有影响，因此决定删除。

In [9]:
#察看hardship字段究竟代表什么意思
df.hardship_flag.value_counts()

N    238540
Y        96
Name: hardship_flag, dtype: int64

从中可以发现，存在困难情况的只有96家，说明数据集中存在困难情况的基本没有，因此可以说明，与困难情况有关系的字段方差过小，在评分卡中毫无区分性，因此不进行分析。

In [10]:
#察看loan_status的内容
df.loan_status.value_counts()

Current               207975
Fully Paid             20419
Late (31-120 days)      4053
In Grace Period         2724
Charged Off             2493
Late (16-30 days)        970
Default                    2
Name: loan_status, dtype: int64

可以看到大部分都是正在还的期限当中或者已经完全付清。在本次评分卡当中，将除了current与fully paid以外的都设置为逾期。

In [11]:
#计算样本之比
(sum(df.loan_status == 'Current')+sum(df.loan_status == 'Fully Paid'))/df.shape[0]

0.9570650351994636

从结果中可以很明显看到数据极度不平衡。

In [12]:
#察看分类数据的情况值
df.select_dtypes(include=['O']).describe().T

,count,unique,top,freq
id,4,4,Total amount funded in policy code 1: 1741781700,1
term,238636,2,36 months,166918
int_rate,238636,75,5.31%,8215
grade,238636,7,B,70728
sub_grade,238636,35,B5,15176
emp_title,218361,71700,Teacher,4295
emp_length,218740,11,10+ years,79521
home_ownership,238636,4,MORTGAGE,113594
verification_status,238636,3,Source Verified,94744
issue_d,238636,6,May-2018,46311
loan_status,238636,7,Current,207975
pymnt_plan,238636,2,n,238561
purpose,238636,13,debt_consolidation,119224
title,238636,12,Debt consolidation,119224
zip_code,238636,886,112xx,2625
addr_state,238636,50,CA,32004
earliest_cr_line,238636,661,Aug-2006,1991
revol_util,238329,1097,0%,2750
initial_list_status,238636,2,w,201922
last_pymnt_d,238300,11,Nov-2018,210429
next_pymnt_d,215724,3,Dec-2018,215676
last_credit_pull_d,238635,13,Nov-2018,223042
application_type,238636,2,Individual,204218
verification_status_joint,33434,3,Not Verified,15111
sec_app_earliest_cr_line,34418,602,Aug-2006,328
hardship_flag,238636,2,N,238540
hardship_type,104,1,INTEREST ONLY-3 MONTHS DEFERRAL,104
hardship_reason,104,7,NATURAL_DISASTER,61
hardship_status,104,3,ACTIVE,96
hardship_start_date,104,5,Oct-2018,56
hardship_end_date,104,5,Jan-2019,41
payment_plan_start_date,104,5,Nov-2018,44
hardship_loan_status,104,4,Current,56
disbursement_method,238636,2,Cash,216966
debt_settlement_flag,238636,2,N,238526
debt_settlement_flag_date,110,7,Nov-2018,48
settlement_status,110,3,ACTIVE,103
settlement_date,110,7,Oct-2018,36

发现：  
1.职业这一栏的种类有点多，不方便建模，需要进行察看。  
2.last_pymnt_d, next_pymnt_d, last_credit_pull_d, initial_list_status, pymnt_plan这几项均属于申请后的信息，与A卡无关，进行删除。  
3.application_type， disbursement_method, debt_settlement_flag这几项unique数少，数据分布极度不平衡，并且，对于了解数据集帮助不大，因此决定删除。  
4.zip_code与addr_state虽然属于贷前信息，但是按照州地区来进行分类，这对于不了解美国经济的我来说，不现实，决定删除。  
5.earliest_cr_line种类过多进行删除。

In [13]:
df.emp_title.value_counts()

Teacher                                    4295
Manager                                    4160
Owner                                      3830
Driver                                     2295
Registered Nurse                           1737
Sales                                      1613
Supervisor                                 1560
RN                                         1498
owner                                      1156
Office Manager                             1156
Project Manager                            1152
General Manager                             956
President                                   939
Director                                    918
Engineer                                    817
Nurse                                       715
Truck Driver                                661
manager                                     655
Operations Manager                          651
Accountant                                  626
teacher                                     610
Server                                      598
Supervisor                                  592
Administrative Assistant                    573
Technician                                  562
Sales Manager                               559
Vice President                              535
Mechanic                                    514
driver                                      513
Attorney                                    504
Manager                                     490
CEO                                         489
Police Officer                              477
Account Manager                             460
Analyst                                     454
Owner                                       432
Store Manager                               416
Software Engineer                           413
Executive Assistant                         412
Foreman                                     411
Truck driver                                408
Paralegal                                   394
Electrician                                 393
Consultant                                  381
Operator                                    353
sales                                       350
Teacher                                     346
Assistant Manager                           343
Controller                                  326
Administrator                               312
Clerk                                       310
Registered nurse                            306
supervisor                                  302
Customer Service                            302
Program Manager                             296
Bartender                                   287
truck driver                                286
Branch Manager                              285
Executive Director                          282
Cook                                        280
IT Manager                                  271
CNA                                         269
Realtor                                     267
Principal                                   260
Maintenance                                 257
Professor                                   256
Director of Operations                      256
Account Executive                           251
Business Analyst                            250
Laborer                                     250
Driver                                      249
Machinist                                   248
Cashier                                     243
Secretary                                   230
Associate                                   226
Superintendent                              224
Maintenance                                 223
Welder                                      221
LPN                                         220
Partner                                     217
Receptionist                                209
Physician                                   209
Legal Assistant                             205
Officer                                     203
Office manager                              200
Medical Assistant                           195
Chef                                        194
Social Worker                               193
Service Manager                             192
Software Developer                          191
Property Manager                            191
Sales                                       189
Superintendent                              188
Sales Associate                             187
Technician                                  185
Senior Manager                              184
Bookkeeper                                  184
Nurse Practitioner                          179
OWNER                                       178
Agent                                       178
                                           ...
Fulfillment                                   1
Chief Nurse Administrator                     1
Deposit Accountant                            1
gm/partner                                    1
Admistrative assistant                        1
Sole proprietor/Attorney at Law               1
Marketing Company President                   1
Commercial General Manager                    1
Operational Risk                              1
CSR supervisor                                1
Administración                                1
Second Secretary                              1
Ass. Principal                                1
body shop painter                             1
Active Duty Military - PMEL                   1
Psych Social Worker                           1
Corporate Legal Administrator                 1
Vice President of Operations/Part-Owner       1
Director of Acct/Hr                           1
HVAC Teck                                     1
Resins Technical Services Manager             1
Front Desk Team Leader                        1
Executive Training Officer                    1
Emergency room physician                      1
Web Developer/Graphic Designer                1
Sr Purchasing Manager                         1
Rehab coordinator/PTA                         1
Terminal Operator                             1
Sr Disaster Recovery Engineer                 1
Insurance sale's agent                        1
Vice President, Asst. General Counsel         1
TRUCK OPERATOR                                1
MLA                                           1
Lead zone supervisor                          1
Bilingual Administrative Assistant            1
Alternate Administrator                       1
Residence program specialist                  1
Nurse Aide Evaluator                          1
accountan                                     1
Center Administrative Assistant               1
Baggage Forman                                1
Teacher Coach                                 1
operator technician 2                         1
Director for Resi Life  Main                  1
Senior forensic engineer                      1
Inventory Production Mgr                      1
Sheet metal installer                         1
Membership coordinator                        1
regional securiy director                     1
Distribution Lead                             1
Register Dental Assistant                     1
Airport Certification Safety Inspector        1
Sterileze Tech II                             1
Materials Mnagement Supervisor                1
service support                               1
eeg tech II                                   1
H B C Cor.                                    1
Marketing Design                              1
SLOT TECH                                     1
Paintless dent removal                        1
BM2                                           1
Supt                                          1
DDO/purser                                    1
Sale operation specialist                     1
Proposal Support Assistant II                 1
RN Educator                                   1
Superindendent                                1
SR. I.T. Operation Support Specialist         1
Corpsmember                                   1
Compliance Educator                           1
FIN REP III                                   1
CLEANING                                      1
Sales & Services/Distribution Associate       1
Account payable specialists                   1
Sr. Maintenance Mechanic                      1
OSD Customer Service Rep                      1
master tech                                   1
HVAC Refrigeration Technician                 1
e-5                                           1
Principal QA Analyst                          1
Business Loan Specialist                      1
dock                                          1
Site Service Technician,                      1
Senior database Administrator                 1
Chef/Cook                                     1
Technical Support Anylst                      1
receptionist manager                          1
Director of Distribution & Logistics          1
Contract Facility Specialist                  1
Cardiac ultrasound tech                       1
 Legal Counsel                                1
Sr Loan Document Specialist                   1
Inspector/Grinder                             1
Judge’s Secretary                             1
Regional O2C Manager                          1
Manufacturing associate                       1
Vice President relationship manager           1
Sr. Plant Accountant                          1
Machine shop supervisor                       1
Graduate Student/Teacher's Assistant          1
Name: emp_title, Length: 71700, dtype: int64

emp_title种类实在太多，并且难以分类，因此删除。

In [14]:
#对于变量类型为float的数据进行察看
df.select_dtypes(include = ['float64']).info(max_cols = 150)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238640 entries, 0 to 238639
Data columns (total 107 columns):
member_id                                     0 non-null float64
loan_amnt                                     238636 non-null float64
funded_amnt                                   238636 non-null float64
funded_amnt_inv                               238636 non-null float64
installment                                   238636 non-null float64
annual_inc                                    238636 non-null float64
url                                           0 non-null float64
desc                                          0 non-null float64
dti                                           238048 non-null float64
delinq_2yrs                                   238636 non-null float64
inq_last_6mths                                238636 non-null float64
mths_since_last_delinq                        105569 non-null float64
mths_since_last_record                        31827 non-null float64
open_acc                                      238636 non-null float64
pub_rec                                       238636 non-null float64
revol_bal                                     238636 non-null float64
total_acc                                     238636 non-null float64
out_prncp                                     238636 non-null float64
out_prncp_inv                                 238636 non-null float64
total_pymnt                                   238636 non-null float64
total_pymnt_inv                               238636 non-null float64
total_rec_prncp                               238636 non-null float64
total_rec_int                                 238636 non-null float64
total_rec_late_fee                            238636 non-null float64
recoveries                                    238636 non-null float64
collection_recovery_fee                       238636 non-null float64
last_pymnt_amnt                               238636 non-null float64
collections_12_mths_ex_med                    238636 non-null float64
mths_since_last_major_derog                   55823 non-null float64
policy_code                                   238636 non-null float64
annual_inc_joint                              34418 non-null float64
dti_joint                                     34418 non-null float64
acc_now_delinq                                238636 non-null float64
tot_coll_amt                                  238636 non-null float64
tot_cur_bal                                   238636 non-null float64
open_acc_6m                                   238636 non-null float64
open_act_il                                   238636 non-null float64
open_il_12m                                   238636 non-null float64
open_il_24m                                   238636 non-null float64
mths_since_rcnt_il                            229315 non-null float64
total_bal_il                                  238636 non-null float64
il_util                                       198600 non-null float64
open_rv_12m                                   238636 non-null float64
open_rv_24m                                   238636 non-null float64
max_bal_bc                                    238636 non-null float64
all_util                                      238573 non-null float64
total_rev_hi_lim                              238636 non-null float64
inq_fi                                        238636 non-null float64
total_cu_tl                                   238636 non-null float64
inq_last_12m                                  238636 non-null float64
acc_open_past_24mths                          238636 non-null float64
avg_cur_bal                                   238621 non-null float64
bc_open_to_buy                                235386 non-null float64
bc_util                                       235283 non-null float64
chargeoff_within_12_mths                      238636 non-null float64
delinq_amnt                                   238636 non-null float64
mo_sin_old_il_acct                            229315 non-null float64
mo_sin_old_rev_tl_op                          238636 non-null float64
mo_sin_rcnt_rev_tl_op                         238636 non-null float64
mo_sin_rcnt_tl                                238636 non-null float64
mort_acc                                      238636 non-null float64
mths_since_recent_bc                          235579 non-null float64
mths_since_recent_bc_dlq                      47516 non-null float64
mths_since_recent_inq                         209394 non-null float64
mths_since_recent_revol_delinq                68827 non-null float64
num_accts_ever_120_pd                         238636 non-null float64
num_actv_bc_tl                                238636 non-null float64
num_actv_rev_tl                               238636 non-null float64
num_bc_sats                                   238636 non-null float64
num_bc_tl                                     238636 non-null float64
num_il_tl                                     238636 non-null float64
num_op_rev_tl                                 238636 non-null float64
num_rev_accts                                 238636 non-null float64
num_rev_tl_bal_gt_0                           238636 non-null float64
num_sats                                      238636 non-null float64
num_tl_120dpd_2m                              232345 non-null float64
num_tl_30dpd                                  238636 non-null float64
num_tl_90g_dpd_24m                            238636 non-null float64
num_tl_op_past_12m                            238636 non-null float64
pct_tl_nvr_dlq                                238635 non-null float64
percent_bc_gt_75                              235381 non-null float64
pub_rec_bankruptcies                          238636 non-null float64
tax_liens                                     238636 non-null float64
tot_hi_cred_lim                               238636 non-null float64
total_bal_ex_mort                             238636 non-null float64
total_bc_limit                                238636 non-null float64
total_il_high_credit_limit                    238636 non-null float64
revol_bal_joint                               34418 non-null float64
sec_app_inq_last_6mths                        34418 non-null float64
sec_app_mort_acc                              34418 non-null float64
sec_app_open_acc                              34418 non-null float64
sec_app_revol_util                            33789 non-null float64
sec_app_open_act_il                           34418 non-null float64
sec_app_num_rev_accts                         34418 non-null float64
sec_app_chargeoff_within_12_mths              34418 non-null float64
sec_app_collections_12_mths_ex_med            34418 non-null float64
sec_app_mths_since_last_major_derog           11611 non-null float64
deferral_term                                 104 non-null float64
hardship_amount                               104 non-null float64
hardship_length                               104 non-null float64
hardship_dpd                                  104 non-null float64
orig_projected_additional_accrued_interest    99 non-null float64
hardship_payoff_balance_amount                104 non-null float64
hardship_last_payment_amount                  104 non-null float64
settlement_amount                             110 non-null float64
settlement_percentage                         110 non-null float64
settlement_term                               110 non-null float64
dtypes: float64(107)
memory usage: 194.8 MB

其中，loan_amnt, funded_amnt, funded_amnt_inv,int_rate, installment, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int, total_rec_late_fee, last_pymnt_amnt这些变量属于申请后信息(贷中，贷后信息)进行删除。当然loan_amnt也应该属于申请信息，按照金额或许可以分类，本次分析不考虑。

In [15]:
#对于变量类型为float的数据进行察看
df.select_dtypes(include = ['float64']).head()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,url,desc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
0,NaN,10000.0,10000.0,10000.0,243.24,42000.0,NaN,NaN,27.06,0.0,0.0,NaN,74.0,9.0,1.0,6434.0,24.0,9079.27,9079.27,1862.16,1862.16,920.73,941.43,0.0,0.0,0.0,243.24,0.0,NaN,1.0,NaN,NaN,0.0,0.0,31425.0,2.0,3.0,0.0,1.0,18.0,24991.0,57.0,2.0,2.0,1186.0,51.0,17800.0,1.0,3.0,0.0,3.0,3492.0,2314.0,33.9,0.0,0.0,161.0,293.0,3.0,3.0,1.0,3.0,NaN,18.0,NaN,0.0,1.0,4.0,1.0,7.0,4.0,6.0,19.0,4.0,9.0,0.0,0.0,0.0,2.0,100.0,0.0,1.0,0.0,61376.0,31425.0,3500.0,43576.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,10000.0,10000.0,10000.0,233.05,42000.0,NaN,NaN,24.69,0.0,0.0,32.0,NaN,17.0,0.0,707.0,34.0,9161.42,9161.42,1664.14,1664.14,838.58,825.56,0.0,0.0,0.0,233.05,0.0,40.0,1.0,NaN,NaN,0.0,0.0,93913.0,0.0,15.0,0.0,0.0,54.0,93206.0,116.0,0.0,1.0,707.0,111.0,4500.0,0.0,0.0,0.0,1.0,5524.0,3793.0,15.7,0.0,0.0,161.0,88.0,18.0,18.0,0.0,18.0,32.0,18.0,32.0,14.0,1.0,1.0,2.0,4.0,30.0,2.0,4.0,1.0,17.0,0.0,0.0,0.0,0.0,43.8,0.0,0.0,0.0,84930.0,93913.0,4500.0,80430.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1000.0,1000.0,1000.0,32.47,44000.0,NaN,NaN,16.37,1.0,1.0,13.0,NaN,9.0,0.0,2748.0,23.0,829.04,829.04,226.13,226.13,170.96,55.17,0.0,0.0,0.0,32.47,0.0,NaN,1.0,NaN,NaN,0.0,0.0,173548.0,1.0,2.0,1.0,3.0,3.0,10298.0,86.0,1.0,2.0,1950.0,52.0,13000.0,3.0,0.0,3.0,6.0,24793.0,1431.0,64.2,0.0,0.0,131.0,210.0,7.0,3.0,2.0,7.0,NaN,4.0,13.0,0.0,2.0,3.0,2.0,4.0,8.0,6.0,13.0,3.0,9.0,0.0,0.0,0.0,2.0,87.0,50.0,0.0,0.0,191866.0,13046.0,4000.0,11996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2600.0,2600.0,2600.0,81.43,62000.0,NaN,NaN,19.61,0.0,0.0,NaN,NaN,8.0,0.0,11776.0,9.0,2141.68,2141.68,567.71,567.71,458.32,109.39,0.0,0.0,0.0,81.43,0.0,NaN,1.0,NaN,NaN,0.0,0.0,241067.0,0.0,2.0,0.0,0.0,34.0,56811.0,13.0,0.0,1.0,7283.0,56.0,15800.0,0.0,0.0,0.0,1.0,30133.0,588.0,94.4,0.0,0.0,79.0,64.0,19.0,19.0,1.0,45.0,NaN,NaN,NaN,0.0,2.0,4.0,2.0,2.0,3.0,5.0,5.0,4.0,8.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,259780.0,68587.0,10500.0,62185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,10000.0,10000.0,10000.0,304.54,175000.0,NaN,NaN,4.94,0.0,0.0,NaN,NaN,12.0,0.0,6885.0,25.0,8195.10,8195.10,2125.04,2125.04,1804.90,320.14,0.0,0.0,0.0,304.54,0.0,NaN,1.0,NaN,NaN,0.0,0.0,318464.0,0.0,2.0,0.0,3.0,16.0,10051.0,27.0,0.0,2.0,3634.0,17.0,60900.0,1.0,1.0,0.0,5.0,28951.0,42115.0,14.1,0.0,0.0,68.0,288.0,17.0,16.0,5.0,17.0,NaN,16.0,NaN,0.0,2.0,2.0,5.0,9.0,4.0,9.0,16.0,2.0,12.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,434276.0,16936.0,49000.0,37376.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.select_dtypes(include = ['float64']).describe().T

,count,mean,std,min,25%,50%,75%,max
member_id,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan_amnt,238636.0,16016.908178,10155.048441,1000.00,8000.0000,14000.000,22000.0000,4.000000e+04
funded_amnt,238636.0,16016.908178,10155.048441,1000.00,8000.0000,14000.000,22000.0000,4.000000e+04
funded_amnt_inv,238636.0,16013.282781,10154.035900,1000.00,8000.0000,14000.000,22000.0000,4.000000e+04
installment,238636.0,466.073304,287.587657,29.76,251.6800,384.850,631.2300,1.628080e+03
annual_inc,238636.0,78609.597862,82886.263205,0.00,45000.0000,65000.000,95000.0000,9.930475e+06
url,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
desc,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dti,238048.0,19.450565,20.559039,0.00,11.1500,17.510,24.8600,9.990000e+02
delinq_2yrs,238636.0,0.230037,0.739554,0.00,0.0000,0.000,0.0000,2.300000e+01
inq_last_6mths,238636.0,0.453662,0.733499,0.00,0.0000,0.000,1.0000,5.000000e+00
mths_since_last_delinq,105569.0,36.784814,21.738464,0.00,19.0000,34.000,53.0000,2.260000e+02
mths_since_last_record,31827.0,81.009992,24.015525,1.00,66.0000,85.000,100.0000,1.270000e+02
open_acc,238636.0,11.413014,5.935516,0.00,7.0000,10.000,14.0000,1.010000e+02
pub_rec,238636.0,0.146801,0.432098,0.00,0.0000,0.000,0.0000,5.200000e+01
revol_bal,238636.0,15785.540027,22474.170853,0.00,5003.0000,10444.000,19258.0000,1.830688e+06
total_acc,238636.0,22.538443,12.098694,2.00,14.0000,20.000,29.0000,1.530000e+02
out_prncp,238636.0,12479.653472,9459.199815,0.00,5089.1700,10261.830,18227.7925,4.000000e+04
out_prncp_inv,238636.0,12476.973353,9458.337623,0.00,5089.1700,10261.130,18224.1375,4.000000e+04
total_pymnt,238636.0,4427.707390,5158.367022,0.00,1757.5900,2982.420,5109.1600,4.637397e+04
total_pymnt_inv,238636.0,4426.587860,5157.400734,0.00,1756.8775,2982.240,5106.3800,4.637397e+04
total_rec_prncp,238636.0,3366.579956,4964.732873,0.00,1128.6500,1904.225,3410.7200,4.000000e+04
total_rec_int,238636.0,1057.935467,923.925824,0.00,388.2000,777.070,1453.2750,9.045670e+03
total_rec_late_fee,238636.0,0.401324,4.817851,0.00,0.0000,0.000,0.0000,3.411600e+02
recoveries,238636.0,2.790644,119.863764,0.00,0.0000,0.000,0.0000,3.312207e+04
collection_recovery_fee,238636.0,0.489836,21.287347,0.00,0.0000,0.000,0.0000,5.961973e+03
last_pymnt_amnt,238636.0,1529.758439,4559.010407,0.00,265.6800,427.390,729.8700,4.135367e+04
collections_12_mths_ex_med,238636.0,0.017147,0.144254,0.00,0.0000,0.000,0.0000,8.000000e+00
mths_since_last_major_derog,55823.0,46.129552,21.412550,0.00,29.0000,46.000,63.0000,2.260000e+02
policy_code,238636.0,1.000000,0.000000,1.00,1.0000,1.000,1.0000,1.000000e+00
annual_inc_joint,34418.0,126019.332193,84583.261214,5693.51,84153.7500,112000.000,150000.0000,7.874821e+06
dti_joint,34418.0,19.497580,8.085445,0.00,13.5300,19.070,25.0800,3.999000e+01
acc_now_delinq,238636.0,0.000109,0.010437,0.00,0.0000,0.000,0.0000,1.000000e+00
tot_coll_amt,238636.0,240.075140,16724.159961,0.00,0.0000,0.000,0.0000,6.214661e+06
tot_cur_bal,238636.0,141832.407420,164704.755777,0.00,26292.5000,73546.000,215066.2500,5.752177e+06
open_acc_6m,238636.0,0.894404,1.123296,0.00,0.0000,1.000,1.0000,1.500000e+01
open_act_il,238636.0,2.665386,2.942770,0.00,1.0000,2.000,3.0000,4.900000e+01
open_il_12m,238636.0,0.666827,0.926741,0.00,0.0000,0.000,1.0000,8.000000e+00
open_il_24m,238636.0,1.506596,1.550081,0.00,0.0000,1.000,2.0000,2.000000e+01
mths_since_rcnt_il,229315.0,21.615995,26.378266,0.00,7.0000,14.000,25.0000,5.070000e+02
total_bal_il,238636.0,34735.182026,44598.925262,0.00,7585.0000,22092.000,45237.0000,1.378570e+06
il_util,198600.0,67.986405,23.950549,0.00,53.0000,70.000,85.0000,1.000000e+03
open_rv_12m,238636.0,1.252602,1.510046,0.00,0.0000,1.000,2.0000,2.600000e+01
open_rv_24m,238636.0,2.673360,2.595601,0.00,1.0000,2.000,4.0000,5.000000e+01
max_bal_bc,238636.0,5691.950770,6066.665635,0.00,2063.0000,4301.000,7564.0000,1.170668e+06
all_util,238573.0,53.831339,21.383123,0.00,39.0000,55.000,69.0000,2.390000e+02
total_rev_hi_lim,238636.0,37591.630462,37346.415466,0.00,15600.0000,28000.000,47800.0000,2.087500e+06
inq_fi,238636.0,1.080009,1.523512,0.00,0.0000,1.000,2.0000,3.800000e+01
total_cu_tl,238636.0,1.460781,2.641285,0.00,0.0000,0.000,2.0000,5.200000e+01
inq_last_12m,238636.0,1.994666,2.417909,0.00,0.0000,1.000,3.0000,6.700000e+01
acc_open_past_24mths,238636.0,4.459139,3.259300,0.00,2.0000,4.000,6.0000,5.400000e+01
avg_cur_bal,238621.0,13652.621257,17188.706952,0.00,2874.0000,6996.000,18969.0000,6.205310e+05
bc_open_to_buy,235386.0,14908.495701,19465.601680,0.00,2781.0000,8087.000,19481.0000,4.931010e+05
bc_util,235283.0,49.363118,29.233996,0.00,25.1000,48.300,74.1000,2.016000e+02
chargeoff_within_12_mths,238636.0,0.006793,0.093046,0.00,0.0000,0.000,0.0000,9.000000e+00
delinq_amnt,238636.0,2.471857,260.756131,0.00,0.0000,0.000,0.0000,6.500000e+04
mo_sin_old_il_acct,229315.0,122.712304,55.415644,1.00,85.0000,129.000,154.0000,5.650000e+02
mo_sin_old_rev_tl_op,238636.0,175.724576,100.682487,1.00,107.0000,158.000,227.0000,8.170000e+02
mo_sin_rcnt_rev_tl_op,238636.0,14.980925,18.713896,0.00,4.0000,9.000,19.0000,5.020000e+02
mo_sin_rcnt_tl,238636.0,8.747544,9.673323,0.00,3.0000,6.000,11.0000,3.680000e+02
mort_acc,238636.0,1.345572,1.713593,0.00,0.0000,1.000,2.0000,4.600000e+01
mths_since_recent_bc,235579.0,25.335790,33.750362,0.00,6.0000,14.000,30.0000,6.610000e+02
mths_since_recent_bc_dlq,47516.0,40.402854,22.202842,0.00,23.0000,38.000,57.0000,1.940000e+02
mths_since_recent_inq,209394.0,7.407442,6.033630,0.00,2.0000,6.000,11.0000,2.500000e+01
mths_since_recent_revol_delinq,68827.0,37.594723,21.918729,0.00,20.0000,35.000,53.0000,1.600000e+02
num_accts_ever_120_pd,238636.0,0.468571,1.364285,0.00,0.0000,0.000,0.0000,4.200000e+01
num_actv_bc_tl,238636.0,3.558034,2.403489,0.00,2.0000,3.000,5.0000,5.000000e+01
num_actv_rev_tl,238636.0,5.285401,3.418799,0.00,3.0000,5.000,7.0000,7.200000e+01
num_bc_sats,238636.0,4.795169,3.162040,0.00,3.0000,4.000,6.0000,6.900000e+01
num_bc_tl,238636.0,7.096084,4.527157,0.00,4.0000,6.000,9.0000,8.600000e+01
num_il_tl,238636.0,8.088587,7.341250,0.00,3.0000,6.000,11.0000,1.160000e+02
num_op_rev_tl,238636.0,8.107251,4.921985,0.00,5.0000,7.000,10.0000,9.100000e+01
num_rev_accts,238636.0,12.903359,7.890833,2.00,7.0000,11.000,17.0000,1.510000e+02
num_rev_tl_bal_gt_0,238636.0,5.244691,3.346800,0.00,3.0000,5.000,7.0000,6.500000e+01
num_sats,238636.0,11.389824,5.928623,0.00,7.0000,10.000,14.0000,1.010000e+02
num_tl_120dpd_2m,232345.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.000000e+00
num_tl_30dpd,238636.0,0.000096,0.009817,0.00,0.0000,0.000,0.0000,1.000000e+00
num_tl_90g_dpd_24m,238636.0,0.059899,0.411689,0.00,0.0000,0.000,0.0000,2.300000e+01
num_tl_op_past_12m,238636.0,2.050877,1.903185,0.00,1.0000,2.000,3.0000,2.600000e+01
pct_tl_nvr_dlq,238635.0,94.533898,9.167572,0.00,92.3000,100.000,100.0000,1.000000e+02
percent_bc_gt_75,235381.0,32.572248,35.017527,0.00,0.0000,25.000,55.6000,1.000000e+02
pub_rec_bankruptcies,238636.0,0.124030,0.336349,0.00,0.0000,0.000,0.0000,7.000000e+00
tax_liens,238636.0,0.022658,0.262748,0.00,0.0000,0.000,0.0000,5.200000e+01
tot_hi_cred_lim,238636.0,182366.261997,185355.488441,0.00,51083.0000,114900.000,265743.2500,6.057411e+06
total_bal_ex_mort,238636.0,50813.391802,52218.116633,0.00,18967.0000,36792.000,64868.5000,1.889666e+06
total_bc_limit,238636.0,26117.919329,25566.201840,0.00,9400.0000,18700.000,34500.0000,1.569000e+06
total_il_high_credit_limit,238636.0,44974.482693,47196.703054,0.00,14500.0000,33180.000,60981.0000,1.665437e+06
revol_bal_joint,34418.0,33951.912604,28221.133338,0.00,15192.7500,26835.000,44208.0000,3.711530e+05
sec_app_inq_last_6mths,34418.0,0.643675,1.010564,0.00,0.0000,0.000,1.0000,6.000000e+00
sec_app_mort_acc,34418.0,1.505259,1.756327,0.00,0.0000,1.000,2.0000,2.700000e+01
sec_app_open_acc,34418.0,11.579377,6.704826,0.00,7.0000,10.000,15.0000,6.600000e+01
sec_app_revol_util,33789.0,58.091435,25.796011,0.00,39.5000,60.200,78.7000,4.343000e+02
sec_app_open_act_il,34418.0,3.027457,3.291157,0.00,1.0000,2.000,4.0000,3.500000e+01
sec_app_num_rev_accts,34418.0,12.622087,8.236240,0.00,7.0000,11.000,17.0000,8.500000e+01
sec_app_chargeoff_within_12_mths,34418.0,0.049364,0.436420,0.00,0.0000,0.000,0.0000,2.000000e+01
sec_app_collections_12_mths_ex_med,34418.0,0.078680,0.425832,0.00,0.0000,0.000,0.0000,2.300000e+01
sec_app_mths_since_last_major_derog,11611.0,36.043579,23.836140,0.00,15.0000,34.000,55.0000,1.850000e+02
deferral_term,104.0,3.000000,0.000000,3.00,3.0000,3.000,3.0000,3.000000e+00
hardship_amount,104.0,205.197692,152.907162,10.55,92.4750,172.545,289.4150,8.452200e+02
hardship_length,104.0,3.000000,0.000000,3.00,3.0000,3.000,3.0000,3.000000e+00
hardship_dpd,104.0,8.259615,9.455050,0.00,0.0000,3.000,16.2500,2.900000e+01
orig_projected_additional_accrued_interest,99.0,620.627273,467.354281,31.65,273.3000,522.150,869.1000,2.535660e+03
hardship_payoff_balance_amount,104.0,16769.639904,10513.563649,620.83,8958.3950,13547.160,25329.8525,3.882441e+04
hardship_last_payment_amount,104.0,204.769904,246.079871,0.07,2.1400,126.950,317.0150,1.072990e+03
settlement_amount,110.0,6842.357636,4618.631777,633.72,3361.2850,5598.930,9320.6850,2.233000e+04
settlement_percentage,110.0,56.651818,9.891926,40.00,45.0000,64.520,65.0000,8.000000e+01
settlement_term,110.0,18.072727,6.002613,1.00,18.0000,18.000,24.0000,2.400000e+01

发现：  
1.member_id,url,desc,mths_since_last_delinq等字段数量较少(小于65%)需要删除。  
2.对于其他的数值型变量使用中位数来进行填充。 
3.发现delinq_2yrs等变量至少有75%或者以上的数据是相同的，这可能是由于数据是不平衡的，需要查看。
4.policy_code，num_tl_120dpd_2m等变量标准差为零，需要删除。

**需要处理的问题归纳**

需要处理的问题汇总：  
1.有4行的数据毫无意义需要删除。    
2.对于困难情况以及其他对于其他的数据量小于65%的字段进行删除。    
3.对于term,grade,sub_grade,issue_d,title均属于贷后数据因此决定删除。  
4.zip_code,addr_state,earliest_cr_line,emp_title种类过多进行字段进行删除。  
5.application_type， disbursement_method, debt_settlement_flag这几项unique数少，数据分布极度不平衡，并且，对于了解数据集帮助不大，因此决定删除。   
6.last_pymnt_d, next_pymnt_d, last_credit_pull_d, initial_list_status, pymnt_plan这几项均属于申请后的信息，与A卡无关，进行删除。  
7.对于loan_amnt, funded_amnt, funded_amnt_inv, int_rate, installment, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int,total_rec_late_fee,last_pymnt_amnt 这些变量进行删除。 
8.emp_length这个字段的缺失值较少的字段的缺失值用unknown来进行填充。   
9.int_rate, revol_util这两个本应该为数字的字段这里是用字符串表示的，为了之后的计算方便，需要更改类型。(由于发现int_rate为贷后字段，只对revol_util进行操作)    
10.对于缺失较少的字段用中位数进行填充。  
11.发现delinq_2yrs等变量至少有75%或者以上的数据是相同的，进行删除。  
12.policy_code，num_tl_120dpd_2m等变量标准差为零，需要删除。  
13.将loan_status中的类别转化为0和1(1代表不良)。

**数据清洗**

In [17]:
#复制数据集
df_clean = df.copy()

1.有4行的数据毫无意义需要删除。

In [18]:
#对于无意义的4行进行删除
df_clean = df_clean.loc[df.id.isnull()]

In [19]:
#确认
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 238636 entries, 0 to 238637
Columns: 145 entries, id to settlement_term
dtypes: float64(107), object(38)
memory usage: 265.8+ MB

2.对于困难情况以及其他对于其他的数据量小于65%的字段进行删除。

In [20]:
#对于与困难情况相关的字段，以及数据量小于65%的字段进行删除
thr = 0.65
df_clean = df_clean.dropna(thresh = len(df_clean)*thr, axis = 1)
df_clean = df_clean.drop(columns = 'hardship_flag', axis = 1)

3.对于term,grade,sub_grade,issue_d,title均属于贷后数据因此决定删除。

In [21]:
#对于相应字段进行删除
col = ['term','grade','sub_grade','issue_d','title']
df_clean.drop(columns = col, axis = 1, inplace = True)

4.zip_code,addr_state,earliest_cr_line,emp_title种类过多进行字段进行删除。

In [22]:
#对于相应字段进行删除
col = ['zip_code', 'addr_state','earliest_cr_line','emp_title']
df_clean.drop(columns = col, axis = 1, inplace = True)

application_type， disbursement_method, debt_settlement_flag这几项unique数少，数据分布极度不平衡，并且，对于了解数据集帮助不大，因此决定删除。

In [23]:
#对于相应字段进行删除
col = ['application_type', 'disbursement_method', 'debt_settlement_flag']
df_clean.drop(columns = col, axis = 1, inplace = True)

6.last_pymnt_d, next_pymnt_d, last_credit_pull_d, initial_list_status, pymnt_plan这几项均属于申请后的信息，与A卡无关，进行删除。

In [24]:
#对于相应字段进行删除
col = ['last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d', 'initial_list_status', 'pymnt_plan']
df_clean.drop(columns = col, axis = 1, inplace = True)

7.对于loan_amnt, funded_amnt, funded_amnt_inv, int_rate, installment, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int,total_rec_late_fee,last_pymnt_amnt 这些变量进行删除。

In [25]:
col = ['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'int_rate', 'installment', 'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int','total_rec_late_fee','last_pymnt_amnt']
df_clean.drop(columns = col, axis = 1, inplace = True)

8.emp_length这个字段的缺失值较少的字段的缺失值用unknown来进行填充。

In [26]:
#对于emp_title, emp_length的缺失值进行填充
df_clean.emp_length.loc[df_clean.emp_length.isnull()] = 'unknown'

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [27]:
#确认
print(sum(df_clean.emp_length.isnull()))

0

9.int_rate, revol_util这两个本应该为数字的字段这里是用字符串表示的，为了之后的计算方便，需要更改类型。(由于发现int_rate为贷后字段，只对revol_util进行操作)

In [28]:
#用正则表达式提取数字部分,并且赋值
df_clean.revol_util = df_clean.revol_util.str.extract(r'(\d+\.\d+)')
df_clean.revol_util = df_clean.revol_util.astype('float64')

In [29]:
#确认
print(df_clean.revol_util.dtype)

float64

10.对于缺失较少的字段用中位数进行填充。

In [30]:
#用中位数进行填充
for col in df_clean.columns:
    if df_clean[col].isnull().any():
        df_clean[col].fillna(df_clean[col].median(),inplace=True)

In [31]:
#确认
for col in df_clean.columns:
    if df_clean[col].isnull().any():
        print('失败')

11.发现delinq_2yrs等变量至少有75%或者以上的数据是相同的，进行删除。

In [32]:
#删除信息量过少的数据(这里按照第三四分位叔等于最小值来判断)
col = []
for i in df_clean.select_dtypes(include=['float64']).columns:
    if df_clean[i].quantile(.75) == df_clean[i].min():
        col.append(i)
col

['delinq_2yrs',
 'pub_rec',
 'recoveries',
 'collection_recovery_fee',
 'collections_12_mths_ex_med',
 'policy_code',
 'acc_now_delinq',
 'tot_coll_amt',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'num_accts_ever_120_pd',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'pub_rec_bankruptcies',
 'tax_liens']

In [33]:
df_clean.drop(columns=col,inplace=True)

12.policy_code，num_tl_120dpd_2m等变量标准差为零，需要删除。(发现在11中已经完成)

13.将loan_status中的类别转化为0和1(1代表不良)。

In [34]:
df_clean = df_clean.reset_index(drop = True)
count = 0

df_clean['class'] = df_clean.loan_status.apply(lambda x: '0' if x in ('Current', 'Fully Paid') else '1')

In [35]:
#确认
df_clean['class'].value_counts()

0    228394
1     10242
Name: class, dtype: int64

In [36]:
#删除loan_status字段
df_clean.drop(columns = 'loan_status', inplace = True)

In [37]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238636 entries, 0 to 238635
Data columns (total 55 columns):
emp_length                    238636 non-null object
home_ownership                238636 non-null object
annual_inc                    238636 non-null float64
verification_status           238636 non-null object
purpose                       238636 non-null object
dti                           238636 non-null float64
inq_last_6mths                238636 non-null float64
open_acc                      238636 non-null float64
revol_bal                     238636 non-null float64
revol_util                    238636 non-null float64
total_acc                     238636 non-null float64
tot_cur_bal                   238636 non-null float64
open_acc_6m                   238636 non-null float64
open_act_il                   238636 non-null float64
open_il_12m                   238636 non-null float64
open_il_24m                   238636 non-null float64
mths_since_rcnt_il            238636 non-null float64
total_bal_il                  238636 non-null float64
il_util                       238636 non-null float64
open_rv_12m                   238636 non-null float64
open_rv_24m                   238636 non-null float64
max_bal_bc                    238636 non-null float64
all_util                      238636 non-null float64
total_rev_hi_lim              238636 non-null float64
inq_fi                        238636 non-null float64
total_cu_tl                   238636 non-null float64
inq_last_12m                  238636 non-null float64
acc_open_past_24mths          238636 non-null float64
avg_cur_bal                   238636 non-null float64
bc_open_to_buy                238636 non-null float64
bc_util                       238636 non-null float64
mo_sin_old_il_acct            238636 non-null float64
mo_sin_old_rev_tl_op          238636 non-null float64
mo_sin_rcnt_rev_tl_op         238636 non-null float64
mo_sin_rcnt_tl                238636 non-null float64
mort_acc                      238636 non-null float64
mths_since_recent_bc          238636 non-null float64
mths_since_recent_inq         238636 non-null float64
num_actv_bc_tl                238636 non-null float64
num_actv_rev_tl               238636 non-null float64
num_bc_sats                   238636 non-null float64
num_bc_tl                     238636 non-null float64
num_il_tl                     238636 non-null float64
num_op_rev_tl                 238636 non-null float64
num_rev_accts                 238636 non-null float64
num_rev_tl_bal_gt_0           238636 non-null float64
num_sats                      238636 non-null float64
num_tl_op_past_12m            238636 non-null float64
pct_tl_nvr_dlq                238636 non-null float64
percent_bc_gt_75              238636 non-null float64
tot_hi_cred_lim               238636 non-null float64
total_bal_ex_mort             238636 non-null float64
total_bc_limit                238636 non-null float64
total_il_high_credit_limit    238636 non-null float64
class                         238636 non-null object
dtypes: float64(50), object(5)
memory usage: 100.1+ MB

In [38]:
#写入
df_clean.to_csv('../data/rough_clean_data.csv',index = False)